# Step 1 Import Libraries
# decd.co/arules-apriori    for data

In [6]:
import pandas as pd
import matplotlib.pyplot  as plt

# apriori function for frequest itemset and extarct possible rules
from mlxtend.frequent_patterns import apriori , association_rules

In [4]:
data = pd.read_csv("Association Rules - Destination Recommendations - Destinations.csv")

In [5]:
data.head()

,Amsterdam,Barcelona,Berlin,Budapest,Copenhagen,Dublin,Dubrovnik,Edinburgh,Florence,Lisbon,...,Paris,Prague,Reykjavik,Rome,Seville,St Petersburg,Stockholm,Valencia,Venice,Vienna
0,True,True,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,True
3,True,True,True,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
4,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

# Step 3: Model Apriori

### find all frequent item sets using apriori algorith with a given support threshold

In [41]:
frequent_itemsets=apriori(data, min_support=0.01, use_colnames=True)

In [42]:
frequent_itemsets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2427 entries, 0 to 2426
Data columns (total 2 columns):
support     2427 non-null float64
itemsets    2427 non-null object
dtypes: float64(1), object(1)
memory usage: 38.0+ KB

In [43]:
frequent_itemsets.sort_values("support" , ascending=False )

       support                                           itemsets
0     0.625000                                        (Amsterdam)
2     0.333333                                           (Berlin)
10    0.291667                                           (London)
17    0.291667                                             (Rome)
13    0.291667                                            (Milan)
1     0.291667                                        (Barcelona)
22    0.250000                             (Barcelona, Amsterdam)
21    0.208333                                           (Vienna)
8     0.208333                                         (Florence)
119   0.208333                                     (London, Rome)
23    0.208333                                (Berlin, Amsterdam)
41    0.166667                                (Berlin, Barcelona)
146   0.166667                     (Berlin, Barcelona, Amsterdam)
61    0.166667                                   (Berlin, London)
20    0.166667                                           (Venice)
33    0.125000                                 (Milan, Amsterdam)
40    0.125000                                (Vienna, Amsterdam)
123   0.125000                                   (Vienna, London)
85    0.125000                                 (Copenhagen, Rome)
7     0.125000                                        (Edinburgh)
116   0.125000                                    (Milan, London)
69    0.125000                                   (Berlin, Vienna)
133   0.125000                                    (Venice, Milan)
3     0.125000                                         (Budapest)
64    0.125000                                    (Berlin, Paris)
66    0.125000                                     (Berlin, Rome)
15    0.125000                                           (Prague)
111   0.125000                                 (Vienna, Florence)
14    0.125000                                            (Paris)
4     0.125000                                       (Copenhagen)
...        ...                                                ...
882   0.041667   (Copenhagen, Berlin, Barcelona, Amsterdam, Rome)
883   0.041667  (Copenhagen, Berlin, Barcelona, Amsterdam, Sto...
884   0.041667  (Vienna, Copenhagen, Berlin, Barcelona, Amster...
886   0.041667     (Berlin, Barcelona, London, Dublin, Amsterdam)
877   0.041667  (Budapest, Berlin, Barcelona, Amsterdam, Stock...
887   0.041667       (Berlin, Barcelona, Dublin, Amsterdam, Rome)
888   0.041667  (Berlin, Barcelona, Dublin, Amsterdam, Stockholm)
889   0.041667     (Vienna, Berlin, Barcelona, Dublin, Amsterdam)
890   0.041667   (Florence, Madrid, Berlin, Barcelona, Amsterdam)
891   0.041667   (Vienna, Florence, Berlin, Barcelona, Amsterdam)
892   0.041667     (Berlin, Barcelona, Lisbon, London, Amsterdam)
878   0.041667   (Vienna, Budapest, Berlin, Barcelona, Amsterdam)
876   0.041667     (Budapest, Berlin, Barcelona, Amsterdam, Rome)
860   0.041667                    (Venice, Florence, Milan, Rome)
867   0.041667                      (Venice, Milan, London, Rome)
861   0.041667              (Vienna, Florence, Stockholm, Prague)
862   0.041667                  (Lisbon, Stockholm, London, Rome)
863   0.041667                     (Lisbon, Vienna, London, Rome)
864   0.041667                (Lisbon, Stockholm, London, Vienna)
865   0.041667                  (Lisbon, Vienna, Stockholm, Rome)
866   0.041667               (St Petersburg, Milan, London, Rome)
868   0.041667                      (Paris, Prague, London, Rome)
875   0.041667   (Budapest, Berlin, Barcelona, London, Amsterdam)
869   0.041667                (Vienna, Stockholm, London, Prague)
870   0.041667                  (Vienna, Stockholm, London, Rome)
871   0.041667              (Reykjavik, Marseille, Prague, Milan)
872   0.041667  (Budapest, Copenhagen, Berlin, Barcelona, Amst...
873   0.041667   (Budapest, Berlin, Barcelona, Dublin, Amsterdam)
874   0.041667   (Budapest, Berlin, Barcelona, Lisbon, Amsterdam)
2426  0.041667  (Vienna, Budapest, Copenhagen, Berlin, Barcelo...

[2427 rows x 2 columns]

### Now find association rules that can be constructed out of the frequest itemset using a given confidence threshold

In [44]:
rules = association_rules(frequent_itemsets, min_threshold=0.01, metric='confidence')

In [45]:
rules.sort_values("lift", ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
89083,"(Stockholm, Budapest, Rome)","(Vienna, Barcelona, Dublin, Lisbon)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108164,"(Vienna, Lisbon, Barcelona, Berlin, Amsterdam)","(London, Stockholm, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108166,"(Vienna, Berlin, Barcelona, London, Dublin)","(Lisbon, Stockholm, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108167,"(Vienna, Berlin, Barcelona, Dublin, Amsterdam)","(Lisbon, Stockholm, London)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108168,"(Vienna, Berlin, Barcelona, Dublin, Stockholm)","(Lisbon, London, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108169,"(Vienna, Berlin, Barcelona, London, Amsterdam)","(Lisbon, Stockholm, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108170,"(Vienna, Berlin, Barcelona, London, Stockholm)","(Lisbon, Dublin, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108171,"(Vienna, Berlin, Barcelona, Amsterdam, Stockholm)","(London, Lisbon, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108172,"(Vienna, Lisbon, Berlin, London, Dublin)","(Barcelona, Stockholm, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108173,"(Vienna, Lisbon, Berlin, Dublin, Amsterdam)","(Barcelona, Stockholm, London)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108174,"(Vienna, Lisbon, Berlin, Dublin, Stockholm)","(Barcelona, London, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108175,"(Vienna, Lisbon, Berlin, London, Amsterdam)","(Barcelona, Stockholm, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108176,"(Vienna, Lisbon, Berlin, London, Stockholm)","(Barcelona, Dublin, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108177,"(Vienna, Lisbon, Berlin, Amsterdam, Stockholm)","(London, Barcelona, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108178,"(Vienna, Berlin, London, Dublin, Amsterdam)","(Lisbon, Barcelona, Stockholm)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108179,"(Vienna, Berlin, London, Dublin, Stockholm)","(Lisbon, Barcelona, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108180,"(Vienna, Berlin, Dublin, Amsterdam, Stockholm)","(Lisbon, Barcelona, London)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108165,"(Vienna, Lisbon, Barcelona, Berlin, Stockholm)","(London, Dublin, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108163,"(Vienna, Lisbon, Barcelona, Berlin, London)","(Stockholm, Dublin, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108228,"(Amsterdam, Vienna, Dublin, Berlin)","(Lisbon, Barcelona, Stockholm, London)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108162,"(Vienna, Lisbon, Barcelona, Berlin, Dublin)","(Stockholm, London, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108137,"(Vienna, Lisbon, Barcelona, Berlin, London, Am...","(Stockholm, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108138,"(Vienna, Lisbon, Barcelona, Berlin, London, St...","(Dublin, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108139,"(Vienna, Lisbon, Barcelona, Berlin, Amsterdam,...","(London, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108140,"(Vienna, Berlin, Barcelona, London, Dublin, Am...","(Lisbon, Stockholm)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108141,"(Vienna, Berlin, Barcelona, London, Dublin, St...","(Lisbon, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108142,"(Vienna, Berlin, Barcelona, Dublin, Amsterdam,...","(Lisbon, London)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108143,"(Vienna, Berlin, Barcelona, London, Amsterdam,...","(Lisbon, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108144,"(Vienna, Lisbon, Berlin, London, Dublin, Amste...","(Barcelona, Stockholm)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
108146,"(Vienna, Lisbon, Berlin, Dublin, Amsterdam, St...","(Barcelona, London)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf
...,...,...,...,...,...,...,...,...,...
285,"(Barcelona, Amsterdam)",(London),0.250000,0.291667,0.041667,0.166667,0.571429,-0.031250,0.850000
288,(London),"(Barcelona, Amsterdam)",0.291667,0.250000,0.041667,0.142857,0.571429,-0.031250,0.875000
303,"(Barcelona, Amsterdam)",(Milan),0.250000,0.291667,0.041667,0.166667,0.571429,-0.031250,0.850000
306,(Milan),"(Barcelona, Amsterdam)",0.291667,0.250000,0.041667,0.142857,0.571429,-0.031250,0.875000
309,"(Barcelona, Amsterdam)",(Rome),0.250000,0.291667,0.041667,0.166667,0.571429,-0.031250,0.850000
312,(Rome),"(Barcelona, Amsterdam)",0.291667,0.250000,0.041667,0.142857,0.571429,-0.031250,0.875000
26,(Prague),(Amsterdam),0.125000,0.625000,0.041667,0.333333,0.533333,-0.036458,0.562500
374,"(Berlin, Paris)",(Amsterdam),0.125000,0.625000,0.041667,0.333333,0.533333,-0.036458,0.562500
379,(Amsterdam),"(Berlin, Paris)",0.625000,0.125000,0.041667,0.066667,0.533333,-0.036458,0.937500
608,"(Vienna, London)",(Amsterdam),0.125000,0.625000,0.041667,0.333333,0.533333,-0.036458,0.562500
613,(Amsterdam),"(Vienna, London)",0.625000,0.125000,0.041667,0.066667,0.533333,-0.036458,0.937500
655,(Amsterdam),"(Venice, Milan)",0.625000,0.125000,0.041667,0.066667,0.533333,-0.036458,0.937500
27,(Amsterdam),(Prague),0.625000,0.125000,0.041667,0.066667,0.533333,-0.036458,0.937500
650,"(Venice, Milan)",(Amsterdam),0.125000,0.625000,0.041667,0.333333,0.533333,-0.036458,0.562500
25,(Amsterdam),(Paris),0.625000,0.125000,0.041667,0.066667,0.533333,-0.036458,0.937500
24,(Paris),(Amsterdam),0.125000,0.625000,0.041667,0.333333,0.533333,-0.036458,0.562500
58,(Barcelona),(Rome),0.291667,0.291667,0.041667,0.142857,0.489796,-0.043403,0.826389
50,(Barcelona),(London),0.291667,0.291667,0.041667,0.142857,0.489796,-0.043403,0.826389
51,(London),(Barcelona),0.291667,0.291667,0.041667,0.142857,0.489796,-0.043403,0.826389
59,(Rome),(Barcelona),0.291667,0.291667,0.041667,0.142857,0.489796,-0.043403,0.826389
31,(Amsterdam),(Rome),0.625000,0.291667,0.083333,0.133333,0.457143,-0.098958,0.817308
30,(Rome),(Amsterdam),0.291667,0.625000,0.083333,0.285714,0.457143,-0.098958,0.525000
83,(Milan),(Berlin),0.291667,0.333333,0.041667,0.142857,0.428571,-0.055556,0.777778
82,(Berlin),(Milan),0.333333,0.291667,0.041667,0.125000,0.428571,-0.055556,0.809524
367,(Amsterdam),"(Berlin, London)",0.625000,0.166667,0.041667,0.066667,0.400000,-0.062500,0.892857
362,"(Berlin, London)",(Amsterdam),0.166667,0.625000,0.041667,0.250000,0.400000,-0.062500,0.500000
601,(Amsterdam),"(London, Rome)",0.625000,0.208333,0.041667,0.066667,0.320000,-0.088542,0.848214
596,"(London, Rome)",(Amsterdam),0.208333,0.625000,0.041667,0.200000,0.320000,-0.088542,0.468750
17,(Amsterdam),(London),0.625000,0.291667,0.041667,0.066667,0.228571,-0.140625,0.758929
16,(London),(Amsterdam),0.291667,0.625000,0.041667,0.142857,0.228571,-0.140625,0.437500

In [46]:
# create new coloumn to tell us leght of antecedent and consquent

rules["antecedent_len"]=rules["antecedents"].apply(lambda x:len(x))
rules["consequent_len"]=rules["consequents"].apply(lambda x:len(x))

In [48]:
rules.sort_values("lift", ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len,consequent_len
89083,"(Stockholm, Budapest, Rome)","(Vienna, Barcelona, Dublin, Lisbon)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,3,4
108164,"(Vienna, Lisbon, Barcelona, Berlin, Amsterdam)","(London, Stockholm, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108166,"(Vienna, Berlin, Barcelona, London, Dublin)","(Lisbon, Stockholm, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108167,"(Vienna, Berlin, Barcelona, Dublin, Amsterdam)","(Lisbon, Stockholm, London)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108168,"(Vienna, Berlin, Barcelona, Dublin, Stockholm)","(Lisbon, London, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108169,"(Vienna, Berlin, Barcelona, London, Amsterdam)","(Lisbon, Stockholm, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108170,"(Vienna, Berlin, Barcelona, London, Stockholm)","(Lisbon, Dublin, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108171,"(Vienna, Berlin, Barcelona, Amsterdam, Stockholm)","(London, Lisbon, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108172,"(Vienna, Lisbon, Berlin, London, Dublin)","(Barcelona, Stockholm, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108173,"(Vienna, Lisbon, Berlin, Dublin, Amsterdam)","(Barcelona, Stockholm, London)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108174,"(Vienna, Lisbon, Berlin, Dublin, Stockholm)","(Barcelona, London, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108175,"(Vienna, Lisbon, Berlin, London, Amsterdam)","(Barcelona, Stockholm, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108176,"(Vienna, Lisbon, Berlin, London, Stockholm)","(Barcelona, Dublin, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108177,"(Vienna, Lisbon, Berlin, Amsterdam, Stockholm)","(London, Barcelona, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108178,"(Vienna, Berlin, London, Dublin, Amsterdam)","(Lisbon, Barcelona, Stockholm)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108179,"(Vienna, Berlin, London, Dublin, Stockholm)","(Lisbon, Barcelona, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108180,"(Vienna, Berlin, Dublin, Amsterdam, Stockholm)","(Lisbon, Barcelona, London)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108165,"(Vienna, Lisbon, Barcelona, Berlin, Stockholm)","(London, Dublin, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108163,"(Vienna, Lisbon, Barcelona, Berlin, London)","(Stockholm, Dublin, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108228,"(Amsterdam, Vienna, Dublin, Berlin)","(Lisbon, Barcelona, Stockholm, London)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,4,4
108162,"(Vienna, Lisbon, Barcelona, Berlin, Dublin)","(Stockholm, London, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,5,3
108137,"(Vienna, Lisbon, Barcelona, Berlin, London, Am...","(Stockholm, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,6,2
108138,"(Vienna, Lisbon, Barcelona, Berlin, London, St...","(Dublin, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,6,2
108139,"(Vienna, Lisbon, Barcelona, Berlin, Amsterdam,...","(London, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,6,2
108140,"(Vienna, Berlin, Barcelona, London, Dublin, Am...","(Lisbon, Stockholm)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,6,2
108141,"(Vienna, Berlin, Barcelona, London, Dublin, St...","(Lisbon, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,6,2
108142,"(Vienna, Berlin, Barcelona, Dublin, Amsterdam,...","(Lisbon, London)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,6,2
108143,"(Vienna, Berlin, Barcelona, London, Amsterdam,...","(Lisbon, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,6,2
108144,"(Vienna, Lisbon, Berlin, London, Dublin, Amste...","(Barcelona, Stockholm)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,6,2
108146,"(Vienna, Lisbon, Berlin, Dublin, Amsterdam, St...","(Barcelona, London)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,6,2
...,...,...,...,...,...,...,...,...,...,...,...
285,"(Barcelona, Amsterdam)",(London),0.250000,0.291667,0.041667,0.166667,0.571429,-0.031250,0.850000,2,1
288,(London),"(Barcelona, Amsterdam)",0.291667,0.250000,0.041667,0.142857,0.571429,-0.031250,0.875000,1,2
303,"(Barcelona, Amsterdam)",(Milan),0.250000,0.291667,0.041667,0.166667,0.571429,-0.031250,0.850000,2,1
306,(Milan),"(Barcelona, Amsterdam)",0.291667,0.250000,0.041667,0.142857,0.571429,-0.031250,0.875000,1,2
309,"(Barcelona, Amsterdam)",(Rome),0.250000,0.291667,0.041667,0.166667,0.571429,-0.031250,0.850000,2,1
312,(Rome),"(Barcelona, Amsterdam)",0.291667,0.250000,0.041667,0.142857,0.571429,-0.031250,0.875000,1,2
26,(Prague),(Amsterdam),0.125000,0.625000,0.041667,0.333333,0.533333,-0.036458,0.562500,1,1
374,"(Berlin, Paris)",(Amsterdam),0.125000,0.625000,0.041667,0.333333,0.533333,-0.036458,0.562500,2,1
379,(Amsterdam),"(Berlin, Paris)",0.625000,0.125000,0.041667,0.066667,0.533333,-0.036458,0.937500,1,2
608,"(Vienna, London)",(Amsterdam),0.125000,0.625000,0.041667,0.333333,0.533333,-0.036458,0.562500,2,1
613,(Amsterdam),"(Vienna, London)",0.625000,0.125000,0.041667,0.066667,0.533333,-0.036458,0.937500,1,2
655,(Amsterdam),"(Venice, Milan)",0.625000,0.125000,0.041667,0.066667,0.533333,-0.036458,0.937500,1,2
27,(Amsterdam),(Prague),0.625000,0.125000,0.041667,0.066667,0.533333,-0.036458,0.937500,1,1
650,"(Venice, Milan)",(Amsterdam),0.125000,0.625000,0.041667,0.333333,0.533333,-0.036458,0.562500,2,1
25,(Amsterdam),(Paris),0.625000,0.125000,0.041667,0.066667,0.533333,-0.036458,0.937500,1,1
24,(Paris),(Amsterdam),0.125000,0.625000,0.041667,0.333333,0.533333,-0.036458,0.562500,1,1
58,(Barcelona),(Rome),0.291667,0.291667,0.041667,0.142857,0.489796,-0.043403,0.826389,1,1
50,(Barcelona),(London),0.291667,0.291667,0.041667,0.142857,0.489796,-0.043403,0.826389,1,1
51,(London),(Barcelona),0.291667,0.291667,0.041667,0.142857,0.489796,-0.043403,0.826389,1,1
59,(Rome),(Barcelona),0.291667,0.291667,0.041667,0.142857,0.489796,-0.043403,0.826389,1,1
31,(Amsterdam),(Rome),0.625000,0.291667,0.083333,0.133333,0.457143,-0.098958,0.817308,1,1
30,(Rome),(Amsterdam),0.291667,0.625000,0.083333,0.285714,0.457143,-0.098958,0.525000,1,1
83,(Milan),(Berlin),0.291667,0.333333,0.041667,0.142857,0.428571,-0.055556,0.777778,1,1
82,(Berlin),(Milan),0.333333,0.291667,0.041667,0.125000,0.428571,-0.055556,0.809524,1,1
367,(Amsterdam),"(Berlin, London)",0.625000,0.166667,0.041667,0.066667,0.400000,-0.062500,0.892857,1,2
362,"(Berlin, London)",(Amsterdam),0.166667,0.625000,0.041667,0.250000,0.400000,-0.062500,0.500000,2,1
601,(Amsterdam),"(London, Rome)",0.625000,0.208333,0.041667,0.066667,0.320000,-0.088542,0.848214,1,2
596,"(London, Rome)",(Amsterdam),0.208333,0.625000,0.041667,0.200000,0.320000,-0.088542,0.468750,2,1
17,(Amsterdam),(London),0.625000,0.291667,0.041667,0.066667,0.228571,-0.140625,0.758929,1,1
16,(London),(Amsterdam),0.291667,0.625000,0.041667,0.142857,0.228571,-0.140625,0.437500,1,1

In [53]:

# fetch with 1 on LHS and 2 on RHS sorted by lift descenfding
rules[(rules['antecedent_len']==1 ) & (rules['consequent_len'] ==2) ].sort_values("lift", ascending = False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len,consequent_len
841,(Dublin),"(Lisbon, Barcelona)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1397,(Lisbon),"(Vienna, Budapest)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
509,(Dublin),"(London, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
504,(Dublin),"(Lisbon, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
503,(Lisbon),"(Dublin, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1549,(St Petersburg),"(Milan, Copenhagen)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1343,(Lisbon),"(Dublin, Budapest)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1344,(Dublin),"(Lisbon, Budapest)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
845,(Dublin),"(Barcelona, London)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1349,(Dublin),"(London, Budapest)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1596,(Lisbon),"(London, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1458,(Dublin),"(Stockholm, Copenhagen)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1355,(Dublin),"(Budapest, Rome)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1601,(Lisbon),"(Dublin, Rome)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1829,(Lisbon),"(Stockholm, Rome)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
859,(Dublin),"(Barcelona, Stockholm)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1362,(Dublin),"(Stockholm, Budapest)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1313,(Lisbon),"(Budapest, Copenhagen)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1505,(Lisbon),"(Vienna, Copenhagen)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1499,(Lisbon),"(Stockholm, Copenhagen)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1391,(Lisbon),"(Stockholm, Budapest)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1464,(Dublin),"(Vienna, Copenhagen)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1607,(Lisbon),"(Stockholm, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1368,(Dublin),"(Vienna, Budapest)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
852,(Dublin),"(Barcelona, Rome)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1602,(Dublin),"(Lisbon, Rome)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1374,(Dubrovnik),"(Madrid, Budapest)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
839,(Lisbon),"(Barcelona, Dublin)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
671,(Reykjavik),"(Prague, Amsterdam)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
1307,(Dublin),"(Budapest, Copenhagen)",0.041667,0.041667,0.041667,1.000000,24.000000,0.039931,inf,1,2
...,...,...,...,...,...,...,...,...,...,...,...
1745,(Florence),"(London, Rome)",0.208333,0.208333,0.041667,0.200000,0.960000,-0.001736,0.989583,1,2
354,(Florence),"(Berlin, Amsterdam)",0.208333,0.208333,0.041667,0.200000,0.960000,-0.001736,0.989583,1,2
745,(Rome),"(Berlin, Barcelona)",0.291667,0.166667,0.041667,0.142857,0.857143,-0.006944,0.972222,1,2
733,(London),"(Berlin, Barcelona)",0.291667,0.166667,0.041667,0.142857,0.857143,-0.006944,0.972222,1,2
732,(Barcelona),"(Berlin, London)",0.291667,0.166667,0.041667,0.142857,0.857143,-0.006944,0.972222,1,2
1200,(Milan),"(Berlin, London)",0.291667,0.166667,0.041667,0.142857,0.857143,-0.006944,0.972222,1,2
661,(Amsterdam),"(Paris, Rome)",0.625000,0.083333,0.041667,0.066667,0.800000,-0.010417,0.982143,1,2
277,(Amsterdam),"(Barcelona, Florence)",0.625000,0.083333,0.041667,0.066667,0.800000,-0.010417,0.982143,1,2
685,(Amsterdam),"(Venice, Rome)",0.625000,0.083333,0.041667,0.066667,0.800000,-0.010417,0.982143,1,2
469,(Amsterdam),"(London, Copenhagen)",0.625000,0.083333,0.041667,0.066667,0.800000,-0.010417,0.982143,1,2
391,(Amsterdam),"(Berlin, Stockholm)",0.625000,0.083333,0.041667,0.066667,0.800000,-0.010417,0.982143,1,2
691,(Amsterdam),"(Vienna, Rome)",0.625000,0.083333,0.041667,0.066667,0.800000,-0.010417,0.982143,1,2
607,(Amsterdam),"(Stockholm, London)",0.625000,0.083333,0.041667,0.066667,0.800000,-0.010417,0.982143,1,2
559,(Amsterdam),"(Vienna, Edinburgh)",0.625000,0.083333,0.041667,0.066667,0.800000,-0.010417,0.982143,1,2
697,(Amsterdam),"(Vienna, Stockholm)",0.625000,0.083333,0.041667,0.066667,0.800000,-0.010417,0.982143,1,2
307,(Amsterdam),"(Barcelona, Milan)",0.625000,0.083333,0.041667,0.066667,0.800000,-0.010417,0.982143,1,2
535,(Amsterdam),"(Florence, Edinburgh)",0.625000,0.083333,0.041667,0.066667,0.800000,-0.010417,0.982143,1,2
355,(Amsterdam),"(Berlin, Florence)",0.625000,0.083333,0.041667,0.066667,0.800000,-0.010417,0.982143,1,2
349,(Amsterdam),"(Berlin, Edinburgh)",0.625000,0.083333,0.041667,0.066667,0.800000,-0.010417,0.982143,1,2
276,(Florence),"(Barcelona, Amsterdam)",0.208333,0.250000,0.041667,0.200000,0.800000,-0.010417,0.937500,1,2
366,(London),"(Berlin, Amsterdam)",0.291667,0.208333,0.041667,0.142857,0.685714,-0.019097,0.923611,1,2
917,(Barcelona),"(London, Rome)",0.291667,0.208333,0.041667,0.142857,0.685714,-0.019097,0.923611,1,2
306,(Milan),"(Barcelona, Amsterdam)",0.291667,0.250000,0.041667,0.142857,0.571429,-0.031250,0.875000,1,2
288,(London),"(Barcelona, Amsterdam)",0.291667,0.250000,0.041667,0.142857,0.571429,-0.031250,0.875000,1,2
312,(Rome),"(Barcelona, Amsterdam)",0.291667,0.250000,0.041667,0.142857,0.571429,-0.031250,0.875000,1,2
655,(Amsterdam),"(Venice, Milan)",0.625000,0.125000,0.041667,0.066667,0.533333,-0.036458,0.937500,1,2
379,(Amsterdam),"(Berlin, Paris)",0.625000,0.125000,0.041667,0.066667,0.533333,-0.036458,0.937500,1,2
613,(Amsterdam),"(Vienna, London)",0.625000,0.125000,0.041667,0.066667,0.533333,-0.036458,0.937500,1,2
367,(Amsterdam),"(Berlin, London)",0.625000,0.166667,0.041667,0.066667,0.400000,-0.062500,0.892857,1,2
601,(Amsterdam),"(London, Rome)",0.625000,0.208333,0.041667,0.066667,0.320000,-0.088542,0.848214,1,2

In [54]:
rules.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178166 entries, 0 to 178165
Data columns (total 11 columns):
antecedents           178166 non-null object
consequents           178166 non-null object
antecedent support    178166 non-null float64
consequent support    178166 non-null float64
support               178166 non-null float64
confidence            178166 non-null float64
lift                  178166 non-null float64
leverage              178166 non-null float64
conviction            178166 non-null float64
antecedent_len        178166 non-null int64
consequent_len        178166 non-null int64
dtypes: float64(7), int64(2), object(2)
memory usage: 15.0+ MB

In [56]:
rules[rules["antecedents"]=={"Dublin"} ].sort_values("lift", ascending = False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len,consequent_len
39631,(Dublin),"(Budapest, Copenhagen, Berlin, Barcelona, Lisbon)",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,5
65179,(Dublin),"(Vienna, Budapest, Lisbon, Barcelona, Amsterda...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
62281,(Dublin),"(Budapest, Copenhagen, Lisbon, Barcelona, Amst...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
62408,(Dublin),"(Vienna, Budapest, Copenhagen, Lisbon, Barcelo...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
62532,(Dublin),"(Budapest, Copenhagen, Barcelona, London, Amst...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
62658,(Dublin),"(Budapest, Copenhagen, Barcelona, London, Amst...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
62785,(Dublin),"(Vienna, Budapest, Copenhagen, Barcelona, Lond...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
62910,(Dublin),"(Budapest, Copenhagen, Barcelona, Amsterdam, S...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
63037,(Dublin),"(Vienna, Budapest, Copenhagen, Barcelona, Amst...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
63163,(Dublin),"(Vienna, Budapest, Copenhagen, Barcelona, Amst...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
64548,(Dublin),"(Budapest, Lisbon, Barcelona, London, Amsterda...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
64674,(Dublin),"(Budapest, Lisbon, Barcelona, London, Amsterda...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
64801,(Dublin),"(Vienna, Budapest, Lisbon, Barcelona, London, ...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
64926,(Dublin),"(Budapest, Lisbon, Barcelona, Amsterdam, Stock...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
65053,(Dublin),"(Vienna, Budapest, Lisbon, Barcelona, Amsterda...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
65304,(Dublin),"(Budapest, Barcelona, London, Amsterdam, Stock...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
62029,(Dublin),"(Budapest, Copenhagen, Lisbon, Barcelona, Lond...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
65431,(Dublin),"(Vienna, Budapest, Barcelona, London, Amsterda...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
65557,(Dublin),"(Vienna, Budapest, Barcelona, London, Amsterda...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
65682,(Dublin),"(Vienna, Budapest, Barcelona, Amsterdam, Stock...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
66438,(Dublin),"(Copenhagen, Lisbon, Barcelona, London, Amster...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
66564,(Dublin),"(Copenhagen, Lisbon, Barcelona, London, Amster...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
66691,(Dublin),"(Vienna, Copenhagen, Lisbon, Barcelona, London...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
66816,(Dublin),"(Copenhagen, Lisbon, Barcelona, Amsterdam, Sto...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
66943,(Dublin),"(Vienna, Copenhagen, Lisbon, Barcelona, Amster...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
67069,(Dublin),"(Vienna, Copenhagen, Lisbon, Barcelona, Amster...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
67194,(Dublin),"(Copenhagen, Barcelona, London, Amsterdam, Sto...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
67321,(Dublin),"(Vienna, Copenhagen, Barcelona, London, Amster...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
67447,(Dublin),"(Vienna, Copenhagen, Barcelona, London, Amster...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
67572,(Dublin),"(Vienna, Copenhagen, Barcelona, Amsterdam, Sto...",0.041667,0.041667,0.041667,1.0,24.000000,0.039931,inf,1,6
...,...,...,...,...,...,...,...,...,...,...,...
2838,(Dublin),"(Amsterdam, Berlin, Rome)",0.041667,0.083333,0.041667,1.0,12.000000,0.038194,inf,1,3
2684,(Dublin),"(Amsterdam, Berlin, Copenhagen)",0.041667,0.083333,0.041667,1.0,12.000000,0.038194,inf,1,3
2378,(Dublin),"(Vienna, Barcelona, Amsterdam)",0.041667,0.083333,0.041667,1.0,12.000000,0.038194,inf,1,3
6044,(Dublin),"(Berlin, London, Rome)",0.041667,0.083333,0.041667,1.0,12.000000,0.038194,inf,1,3
2601,(Dublin),"(Berlin, Budapest, Amsterdam)",0.041667,0.083333,0.041667,1.0,12.000000,0.038194,inf,1,3
6072,(Dublin),"(Berlin, London, Vienna)",0.041667,0.083333,0.041667,1.0,12.000000,0.038194,inf,1,3
8630,(Dublin),"(Amsterdam, Vienna, Barcelona, Berlin)",0.041667,0.083333,0.041667,1.0,12.000000,0.038194,inf,1,4
1651,(Dublin),"(Vienna, Stockholm)",0.041667,0.083333,0.041667,1.0,12.000000,0.038194,inf,1,2
6116,(Dublin),"(Berlin, Stockholm, Vienna)",0.041667,0.083333,0.041667,1.0,12.000000,0.038194,inf,1,3
1625,(Dublin),"(Stockholm, London)",0.041667,0.083333,0.041667,1.0,12.000000,0.038194,inf,1,2
2153,(Dublin),"(Barcelona, Budapest, Amsterdam)",0.041667,0.083333,0.041667,1.0,12.000000,0.038194,inf,1,3
1631,(Dublin),"(Vienna, London)",0.041667,0.125000,0.041667,1.0,8.000000,0.036458,inf,1,2
98,(Dublin),(Budapest),0.041667,0.125000,0.041667,1.0,8.000000,0.036458,inf,1,1
1092,(Dublin),"(Berlin, Vienna)",0.041667,0.125000,0.041667,1.0,8.000000,0.036458,inf,1,2
1080,(Dublin),"(Berlin, Rome)",0.041667,0.125000,0.041667,1.0,8.000000,0.036458,inf,1,2
528,(Dublin),"(Vienna, Amsterdam)",0.041667,0.125000,0.041667,1.0,8.000000,0.036458,inf,1,2
1451,(Dublin),"(Rome, Copenhagen)",0.041667,0.125000,0.041667,1.0,8.000000,0.036458,inf,1,2
114,(Dublin),(Copenhagen),0.041667,0.125000,0.041667,1.0,8.000000,0.036458,inf,1,1
715,(Dublin),"(Berlin, Barcelona)",0.041667,0.166667,0.041667,1.0,6.000000,0.034722,inf,1,2
1073,(Dublin),"(Berlin, London)",0.041667,0.166667,0.041667,1.0,6.000000,0.034722,inf,1,2
2028,(Dublin),"(Berlin, Barcelona, Amsterdam)",0.041667,0.166667,0.041667,1.0,6.000000,0.034722,inf,1,3
1619,(Dublin),"(London, Rome)",0.041667,0.208333,0.041667,1.0,4.800000,0.032986,inf,1,2
342,(Dublin),"(Berlin, Amsterdam)",0.041667,0.208333,0.041667,1.0,4.800000,0.032986,inf,1,2
145,(Dublin),(Vienna),0.041667,0.208333,0.041667,1.0,4.800000,0.032986,inf,1,1
270,(Dublin),"(Barcelona, Amsterdam)",0.041667,0.250000,0.041667,1.0,4.000000,0.031250,inf,1,2
45,(Dublin),(Barcelona),0.041667,0.291667,0.041667,1.0,3.428571,0.029514,inf,1,1
138,(Dublin),(London),0.041667,0.291667,0.041667,1.0,3.428571,0.029514,inf,1,1
140,(Dublin),(Rome),0.041667,0.291667,0.041667,1.0,3.428571,0.029514,inf,1,1
71,(Dublin),(Berlin),0.041667,0.333333,0.041667,1.0,3.000000,0.027778,inf,1,1
8,(Dublin),(Amsterdam),0.041667,0.625000,0.041667,1.0,1.600000,0.015625,inf,1,1

In [ ]:
# learn eclat